Repository DEU-WebMail-System/WebMail-System, pull requests merged in 2023-05, with the labels that each got.

#8 fix : 뒤로가기 시, 세션은 없지만 이전 내용을 볼 수 있는 문제 처리 (#6)
  src/main/java/deu/cse/spring_webmail/control/SystemController.java
  src/main/webapp/WEB-INF/views/header.jspf
  src/main/webapp/WEB-INF/views/session_timeout.jsp
  target/spring_webmail-0.0.1-SNAPSHOT/WEB-INF/views/session_timeout.jsp
Labels: 🚬김준🚬, 🔨Fix

#9 fix : url을 통해 각 페이지에 권한 없이 접근 가능하여 세션 확인을 통한 접근 방지(#7)
  src/main/java/deu/cse/spring_webmail/WebMvcConfig.java
  src/main/java/deu/cse/spring_webmail/interceptor.java
  src/main/resources/static/css/main_style.css
  src/main/webapp/WEB-INF/views/admin/add_user.jsp
  src/main/webapp/WEB-INF/views/admin/admin_menu.jsp
  src/main/webapp/WEB-INF/views/admin/delete_user.jsp
  src/main/webapp/WEB-INF/views/login_fail.jsp
  src/main/webapp/WEB-INF/views/main_menu.jsp
  src/main/webapp/WEB-INF/views/read_mail/show_message.jsp
  src/main/webapp/WEB-INF/views/read_mail/sidebar_read_menu.jsp
  target/classes/application.properties
  target/classes/deu/cse/spring_webmail/WebMvcConfig.class
  target/classes/deu/cse/spring_webmail/control/SystemController.class
  target/classes/deu/cse/spring_webmail/interceptor.class
  target/classes/deu/cse/spring_webmail/model/Pop3Agent.class
  target/classes/static/css/main_style.css
  target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  target/spring_webmail-0.0.1-SNAPSHOT/WEB-INF/classes/application.properties
  target/spring_webmail-0.0.1-SNAPSHOT/WEB-INF/classes/static/css/main_style.css
  target/spring_webmail-0.0.1-SNAPSHOT/WEB-INF/views/admin/add_user.jsp
  target/spring_webmail-0.0.1-SNAPSHOT/WEB-INF/views/admin/admin_menu.jsp
  target/spring_webmail-0.0.1-SNAPSHOT/WEB-INF/views/admin/delete_user.jsp
  target/spring_webmail-0.0.1-SNAPSHOT/WEB-INF/views/header.jspf
  target/spring_webmail-0.0.1-SNAPSHOT/WEB-INF/views/login_fail.jsp
  target/spring_webmail-0.0.1-SNAPSHOT/WEB-INF/views/main_menu.jsp
  target/spring_webmail-0.0.1-SNAPSHOT/WEB-INF/views/read_mail/show_message.jsp
  target/spring_webmail-0.0.1-SNAPSHOT/WEB-INF/views/read_mail/sidebar_read_menu.jsp
Labels: 🚬김준🚬, 🔨Fix

#11 chore : properties의 하드 코딩된 정보 암호화 하기 (#10)
  key.txt
  pom.xml
  src/main/java/deu/cse/spring_webmail/SpringWebmailApplication.java
  src/main/java/deu/cse/spring_webmail/secure/JasyptConfig.java
  src/main/resources/application.properties
  src/main/resources/config.properties
  src/main/resources/system.properties
Labels: 🚬김준🚬, 🔨Fix

#16 feat : 메일 목록 페이징 처리 기능 구현 (#15)
  src/main/java/deu/cse/spring_webmail/control/SystemController.java
  src/main/java/deu/cse/spring_webmail/model/Pop3Agent.java
  src/main/resources/static/css/main_style.css
  src/main/webapp/WEB-INF/views/main_menu.jsp
Labels: 🧊Feature, 🚬김준🚬

#13 [feat] 주소록 기능 구현 (#12)
  mvnw
  src/main/java/deu/cse/spring_webmail/control/SystemController.java
  src/main/java/deu/cse/spring_webmail/model/AddrbookAgent.java
  src/main/webapp/WEB-INF/tags/addrbook.tag
  src/main/webapp/WEB-INF/views/add_book.jsp
  src/main/webapp/WEB-INF/views/del_book.jsp
  src/main/webapp/WEB-INF/views/mod_book.jsp
  src/main/webapp/WEB-INF/views/read_book.jsp
  src/main/webapp/WEB-INF/views/search_book.jsp
  src/main/webapp/WEB-INF/views/sidebar_menu.jsp
Labels: 🧊Feature, 🪁주혁🪁

#22 fix : local에서도 실행되고, war파일로 배포 시에도 key파일을 찾을 수 있도록 변경(#21)
  src/main/java/deu/cse/spring_webmail/secure/JasyptConfig.java
  src/main/resources/key.txt
Labels: 🚬김준🚬, 🔨Fix

#24 fix: 주소록 관련 버그 수정 (#19)
  src/main/java/deu/cse/spring_webmail/control/SystemController.java
  src/main/java/deu/cse/spring_webmail/model/AddrbookAgent.java
  src/main/webapp/WEB-INF/views/add_book.jsp
  src/main/webapp/WEB-INF/views/del_book.jsp
  src/main/webapp/WEB-INF/views/mod_book.jsp
  src/main/webapp/WEB-INF/views/search_book.jsp
  src/main/webapp/WEB-INF/views/sidebar_menu.jsp
Labels: 💚상혁💚, 🔨Fix
